# Generated by Django 3.0 on 2019-12-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0001_initial'),
        ('malquileres', '0002_remove_alquiler_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='maquinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='maquinaria.Maquinaria'),
            preserve_default=False,
        ),
    ]
