# Generated by Django 3.0 on 2019-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinaria/fotos')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Maquinaria Pesada'), (3, 'Maquinaria Liviana'), (5, 'Herramienta de mano')], default=5)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Disponible'), (0, 'No Disponible')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Maquinarias',
            },
        ),
    ]
